//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEscolar.Models
{
    using ControlEscolar.Models.Entidades;
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int Ins_Id { get; set; }
        public Nullable<int> Ins_Alumno_Id { get; set; }
        public Nullable<int> Ins_Grupo_Id { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grupo Grupo { get; set; }
    }
}
